apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-06-27T02:51:50Z"
  labels:
    app: datatx
  name: datatx
  namespace: default
  resourceVersion: "11236"
  uid: 07631c32-a2d7-4ff3-950e-674138757dfd
spec:
  clusterIP: 10.99.180.197
  clusterIPs:
  - 10.99.180.197
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30698
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: datatx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
