apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-06-29T00:31:28Z"
  generation: 1
  labels:
    app: datatx
  name: datatx
  namespace: argocd
  resourceVersion: "61991"
  uid: 0b7c4102-dca9-42d2-be28-f7d6a766e489
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datatx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datatx
    spec:
      containers:
      - image: docker.io/karmegamp/datatx:v1
        imagePullPolicy: IfNotPresent
        name: datatx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-29T00:31:29Z"
    lastUpdateTime: "2025-06-29T00:31:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-29T00:31:28Z"
    lastUpdateTime: "2025-06-29T00:31:29Z"
    message: ReplicaSet "datatx-84cdfc479f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
